# Generated by Django 6.1 on 2026-08-14 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('author_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('condition', models.CharField(choices=[('new', 'Yeni'), ('like_new', 'Yeni kimi'), ('medium', 'Orta'), ('like_old', 'Köhnə kimi'), ('old', 'Köhnə')], default='medium', max_length=20)),
                ('genre', models.CharField(choices=[('fiction', 'Bədii'), ('fantasy', 'Fantastika'), ('science_fiction', 'Elmi fantastika'), ('mystery', 'Detektiv'), ('thriller', 'Triller'), ('romance', 'Romantik'), ('horror', 'Qorxu'), ('history', 'Tarix'), ('biography', 'Bioqrafiya'), ('self_help', 'Şəxsi inkişaf'), ('philosophy', 'Fəlsəfə'), ('psychology', 'Psixologiya'), ('science', 'Elmi'), ('business', 'Biznes'), ('children', 'Uşaq ədəbiyyatı')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('favorite_users', models.ManyToManyField(blank=True, related_name='favorite_books', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
