# Generated by Django 6.1 on 2026-08-14 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_slug_bookimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Books'},
        ),
    ]
