# Generated by Django 6.1 on 2026-08-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('az', 'Azərbaycan'), ('en', 'İngilis'), ('ru', 'Rus'), ('tr', 'Türk')], default='az', max_length=5),
        ),
    ]
