# Generated by Django 6.1 on 2026-08-14 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='password_change_date',
            new_name='password_change_period_start',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
