"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-lgrq7z917bc$(%+i7vi_8#-oskxr6kmqxb+0c&*5pzvq5d9fsu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.dev',
]# Ngrok-dan gələn POST sorğularını bloklamamaq üçün

# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Local apps
    'accounts',
    'books',
    'messaging',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Kökdəki templates qovluğunu göstərir
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'accounts.context_processors.unread_message_count',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'core.wsgi.application'
ASGI_APPLICATION = 'core.asgi.application'

# Redis Channels Layer (WebSockets üçün Redis konfiqurasiyası)
# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {
#             "hosts": [("127.0.0.1", 6379)], # Lokal Redis serveri
#         },
#     },
# }



CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}

# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'accounts.validators.ComplexPasswordValidator',
    },
]


# Custom User Model
AUTH_USER_MODEL = "accounts.CustomUser"


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'az'  # Azərbaycan dilinə uyğunlaşdırıldı

TIME_ZONE = 'Asia/Baku'  # Yerli saat qurşağına uyğunlaşdırıldı

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

# Kökdəki static qovluğunu göstərir
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Production rejimi üçün (collectstatic əmri zamanı yığılacaq qovluq)
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Media files (İstifadəçilərin yüklədiyi kitab şəkilləri, profil fotoları)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1", # Redis lokalda işləməlidir
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailModelBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# core/settings.py
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/2' # 2-ci bazanı istifadə edirik ki, cache ilə qarışmasın
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'


WEBPUSH_SETTINGS = {
    "VAPID_PUBLIC_KEY": "BOrNU-RcyUHECHzQULJOkNoEgO7l3UIzX4CuCzqcGVqZVuWZxW5pRI0fVAXqnFBLrnhTB-o107MyF1ReyEe2eHQ",
    "VAPID_PRIVATE_KEY": "BKjY_DsX9jk9xPeghVTwqgsi10qicyS2sv0qeRHtmvg",
    "VAPID_ADMIN_EMAIL": "mailto:admin@2tab.az",
}

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'